cat ../index.html > mainmenu.html
cat ../index.html > srchhelp_X_nojavascript.html
cat ../index.html > opacmenu.html
cat ../index.html > srchhelp_erm.html
cat ../index.html > srchhelp_a.html
cat ../index.html > srchhelp_b.html
cat ../index.html > srchhelp_c.html
cat ../index.html > srchhelp_d.html
cat ../index.html > srchhelp_e.html
cat ../index.html > srchhelp_f.html
cat ../index.html > srchhelp_g.html
cat ../index.html > srchhelp_h.html
cat ../index.html > srchhelp_i.html
cat ../index.html > srchhelp_j.html
cat ../index.html > srchhelp_k.html
cat ../index.html > srchhelp_l.html
cat ../index.html > srchhelp_m.html
cat ../index.html > srchhelp_n.html
cat ../index.html > srchhelp_o.html
cat ../index.html > srchhelp_p.html
cat ../index.html > srchhelp_q.html
cat ../index.html > srchhelp_r.html
cat ../index.html > srchhelp_s.html
cat ../index.html > srchhelp_t.html
cat ../index.html > srchhelp_u.html
cat ../index.html > srchhelp_v.html
cat ../index.html > srchhelp_w.html
cat ../index.html > srchhelp_x.html
cat ../index.html > srchhelp_y.html
cat ../index.html > srchhelp_z.html
cat ../index.html > srchhelp_X.html
cat ../index.html > srchhelp_Y.html
